
import java.sql.*;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RAVISH
 */
public class Book_a_Ticket extends javax.swing.JFrame {
    private Connection con=null;
    private Statement stmt=null;
    private String query=null;
    private ResultSet rs;

    /**
     * Creates new form Book_a_Ticket
     */
    public Book_a_Ticket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        FROM_STN = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        TO_STN = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        SEARCH_TRAIN_BTN = new javax.swing.JButton();
        RESET_BTN_1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        CLASS_1 = new javax.swing.JRadioButton();
        CLASS_2 = new javax.swing.JRadioButton();
        CLASS_3 = new javax.swing.JRadioButton();
        DOJ_TextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ENTER_PAXDETAILS_BTN = new javax.swing.JButton();
        TRAIN_NO = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        NO_OF_ADULTS = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        NO_OF_CHILD = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        PAX_1_NAME = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        PAX_1_AGE = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        PAX_1_GENDER = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        PAX_1_UID = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        PAX_2_NAME = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        PAX_2_AGE = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        PAX_2_GENDER = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        PAX_2_UID = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        PAX_3_NAME = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        PAX_3_AGE = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        PAX_3_GENDER = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        PAX_3_UID = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        PAX_4_NAME = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        PAX_4_AGE = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        PAX_4_GENDER = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        PAX_4_UID = new javax.swing.JTextField();
        BOOK_TICKET_BTN = new javax.swing.JButton();
        RESET_BTN_2 = new javax.swing.JButton();
        MAIN_PAGE_BTN = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        TOTAL_FARE = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        FARE_BTN = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        Ticket_No = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        PRINT_TICKET_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INDIAN RAILWAYS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("INDIAN RAILWAYS");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setText("BULLET TRAIN RESERVATION CUM ENQUIRY SYSTEM");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap(884, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("[NDLS] NEW DELHI JN.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("!! WELCOME TO INDIAN RAILWAYS !!");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("SERVER 1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(325, 325, 325)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(jLabel6)
                .addComponent(jLabel7))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BOOK A TICKET", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("FROM:");
        jLabel8.setToolTipText("");

        FROM_STN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FROM_STN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AHMEDABAD - (ADI)", "BANGLORE CITY - (SBC)", "CHENNAI CENTRAL - (MAS)", "JAIPUR - (JP)", "KANPUR CENTRAL - (CNB)", "KOLKATA - (KOAA)", "MUMBAI CENTRAL - (BCT)", "NEW DELHI JN - (NDLS)", "PATNA - (PNBE)" }));
        FROM_STN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FROM_STNActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("TO:");
        jLabel9.setToolTipText("");

        TO_STN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TO_STN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AHMEDABAD - (ADI)", "BANGLORE CITY - (SBC)", "CHENNAI CENTRAL - (MAS)", "JAIPUR - (JP)", "KANPUR CENTRAL - (CNB)", "KOLKATA - (KOAA)", "MUMBAI CENTRAL - (BCT)", "NEW DELHI JN - (NDLS)", "PATNA - (PNBE)" }));
        TO_STN.setToolTipText("");
        TO_STN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TO_STNActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("TRAIN NO:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("D.O.J:");

        SEARCH_TRAIN_BTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SEARCH_TRAIN_BTN.setText("SEARCH TRAINS");
        SEARCH_TRAIN_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_TRAIN_BTNActionPerformed(evt);
            }
        });

        RESET_BTN_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RESET_BTN_1.setText("RESET");
        RESET_BTN_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESET_BTN_1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("CLASS:");

        buttonGroup1.add(CLASS_1);
        CLASS_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CLASS_1.setText("FIRST CLASS");
        CLASS_1.setEnabled(false);

        buttonGroup1.add(CLASS_2);
        CLASS_2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CLASS_2.setText("EXECUTIVE CLASS");
        CLASS_2.setEnabled(false);

        buttonGroup1.add(CLASS_3);
        CLASS_3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CLASS_3.setText("ECONOMY");
        CLASS_3.setEnabled(false);

        DOJ_TextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("(YYYY-MM-DD)");

        ENTER_PAXDETAILS_BTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ENTER_PAXDETAILS_BTN.setText("ENTER PASSENGER'S DETAILS");
        ENTER_PAXDETAILS_BTN.setEnabled(false);
        ENTER_PAXDETAILS_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENTER_PAXDETAILS_BTNActionPerformed(evt);
            }
        });

        TRAIN_NO.setEditable(false);
        TRAIN_NO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(SEARCH_TRAIN_BTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RESET_BTN_1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TO_STN, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FROM_STN, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(DOJ_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(TRAIN_NO, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CLASS_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CLASS_2)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CLASS_3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ENTER_PAXDETAILS_BTN)
                .addGap(68, 68, 68))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(FROM_STN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TO_STN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(DOJ_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SEARCH_TRAIN_BTN)
                    .addComponent(RESET_BTN_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TRAIN_NO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CLASS_1)
                    .addComponent(CLASS_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CLASS_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(ENTER_PAXDETAILS_BTN))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PASSENGER'S DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("NO.OF ADULTS");

        NO_OF_ADULTS.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NO_OF_ADULTS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        NO_OF_ADULTS.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("NO.OF CHILD");

        NO_OF_CHILD.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NO_OF_CHILD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        NO_OF_CHILD.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Age>12years");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Age<12years");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("PASSENGER DETAIL'S");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("NAME:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("1.");

        PAX_1_NAME.setEditable(false);
        PAX_1_NAME.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("AGE:");

        PAX_1_AGE.setEditable(false);
        PAX_1_AGE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("GENDER:");

        PAX_1_GENDER.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PAX_1_GENDER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHER", " " }));
        PAX_1_GENDER.setSelectedIndex(3);
        PAX_1_GENDER.setEnabled(false);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("AADHAR NO.");

        PAX_1_UID.setEditable(false);
        PAX_1_UID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("2.");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("NAME:");

        PAX_2_NAME.setEditable(false);
        PAX_2_NAME.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("AGE:");

        PAX_2_AGE.setEditable(false);
        PAX_2_AGE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("GENDER:");

        PAX_2_GENDER.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PAX_2_GENDER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHER", " " }));
        PAX_2_GENDER.setSelectedIndex(3);
        PAX_2_GENDER.setEnabled(false);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("AADHAR NO.");

        PAX_2_UID.setEditable(false);
        PAX_2_UID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("3.");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("NAME:");

        PAX_3_NAME.setEditable(false);
        PAX_3_NAME.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("AGE:");

        PAX_3_AGE.setEditable(false);
        PAX_3_AGE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setText("GENDER:");

        PAX_3_GENDER.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PAX_3_GENDER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHER", " " }));
        PAX_3_GENDER.setSelectedIndex(3);
        PAX_3_GENDER.setEnabled(false);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setText("AADHAR NO.");

        PAX_3_UID.setEditable(false);
        PAX_3_UID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setText("4.");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setText("NAME:");

        PAX_4_NAME.setEditable(false);
        PAX_4_NAME.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setText("AGE:");

        PAX_4_AGE.setEditable(false);
        PAX_4_AGE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setText("GENDER:");

        PAX_4_GENDER.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PAX_4_GENDER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHER", " " }));
        PAX_4_GENDER.setSelectedIndex(3);
        PAX_4_GENDER.setEnabled(false);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setText("AADHAR NO.");

        PAX_4_UID.setEditable(false);
        PAX_4_UID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NO_OF_ADULTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(230, 230, 230)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NO_OF_CHILD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addGap(119, 119, 119))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PAX_1_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PAX_1_AGE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PAX_1_GENDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PAX_1_UID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PAX_2_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PAX_2_AGE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PAX_2_GENDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PAX_2_UID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PAX_3_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PAX_3_AGE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PAX_3_GENDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PAX_3_UID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PAX_4_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PAX_4_AGE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PAX_4_GENDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PAX_4_UID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(NO_OF_ADULTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(NO_OF_CHILD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(PAX_1_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(PAX_1_AGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(PAX_1_GENDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(PAX_1_UID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24)
                    .addComponent(PAX_2_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(PAX_2_AGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(PAX_2_GENDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(PAX_2_UID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel29)
                    .addComponent(PAX_3_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(PAX_3_AGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(PAX_3_GENDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(PAX_3_UID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel34)
                    .addComponent(PAX_4_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(PAX_4_AGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(PAX_4_GENDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(PAX_4_UID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BOOK_TICKET_BTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BOOK_TICKET_BTN.setText("BOOK TICKET");
        BOOK_TICKET_BTN.setEnabled(false);
        BOOK_TICKET_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOOK_TICKET_BTNActionPerformed(evt);
            }
        });

        RESET_BTN_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RESET_BTN_2.setText("RESET");
        RESET_BTN_2.setEnabled(false);
        RESET_BTN_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESET_BTN_2ActionPerformed(evt);
            }
        });

        MAIN_PAGE_BTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MAIN_PAGE_BTN.setText("<< BACK TO MAIN PAGE");
        MAIN_PAGE_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAIN_PAGE_BTNActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TOTAL_FARE.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        TOTAL_FARE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TOTAL_FARE, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TOTAL_FARE, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel40.setText("Total Fare:");

        FARE_BTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FARE_BTN.setText("CALCULATE FARE:");
        FARE_BTN.setEnabled(false);
        FARE_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FARE_BTNActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setText("ENTER TICKET NO.");

        Ticket_No.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ticket_No, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(Ticket_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PRINT_TICKET_BTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PRINT_TICKET_BTN.setText("PRINT TICKET");
        PRINT_TICKET_BTN.setEnabled(false);
        PRINT_TICKET_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRINT_TICKET_BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FARE_BTN)
                        .addGap(327, 327, 327)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
            .addComponent(jSeparator3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(MAIN_PAGE_BTN)
                .addGap(177, 177, 177)
                .addComponent(BOOK_TICKET_BTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PRINT_TICKET_BTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RESET_BTN_2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel40)
                                    .addComponent(FARE_BTN))
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MAIN_PAGE_BTN)
                    .addComponent(BOOK_TICKET_BTN)
                    .addComponent(RESET_BTN_2)
                    .addComponent(PRINT_TICKET_BTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TO_STNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TO_STNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TO_STNActionPerformed

    private void SEARCH_TRAIN_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_TRAIN_BTNActionPerformed
        // TODO add your handling code here:
        if (FROM_STN.getSelectedIndex()==0 && TO_STN.getSelectedIndex()==0) 
        {
            JOptionPane.showMessageDialog(null,"[FROM] Station and [TO] Station can't be Same!"
                    + "   Please Try Again!!",
                    "Invalid Selection",JOptionPane.ERROR_MESSAGE);
        }
        else if (FROM_STN.getSelectedIndex()==1 && TO_STN.getSelectedIndex()==1) 
        {
            JOptionPane.showMessageDialog(null,"[FROM] Station and [TO] Station can't be Same!"
                    + "   Please Try Again!!",
                    "Invalid Selection",JOptionPane.ERROR_MESSAGE);
        }
        else if (FROM_STN.getSelectedIndex()==2 && TO_STN.getSelectedIndex()==2)
        {
            JOptionPane.showMessageDialog(null,"[FROM] Station and [TO] Station can't be Same!"
                    + "   Please Try Again!!",
                    "Invalid Selection",JOptionPane.ERROR_MESSAGE);
        }
        else if (FROM_STN.getSelectedIndex()==3 && TO_STN.getSelectedIndex()==3) 
        {
            JOptionPane.showMessageDialog(null,"[FROM] Station and [TO] Station can't be Same!"
                    + "   Please Try Again!!",
                    "Invalid Selection",JOptionPane.ERROR_MESSAGE);
        }
        else if (FROM_STN.getSelectedIndex()==4 && TO_STN.getSelectedIndex()==4) 
        {
            JOptionPane.showMessageDialog(null,"[FROM] Station and [TO] Station can't be Same!"
                    + "   Please Try Again!!",
                    "Invalid Selection",JOptionPane.ERROR_MESSAGE);
        }
        else if (FROM_STN.getSelectedIndex()==5 && TO_STN.getSelectedIndex()==5) 
        {
            JOptionPane.showMessageDialog(null,"[FROM] Station and [TO] Station can't be Same!"
                    + "   Please Try Again!!",
                    "Invalid Selection",JOptionPane.ERROR_MESSAGE);
        }
        else if (FROM_STN.getSelectedIndex()==6 && TO_STN.getSelectedIndex()==6) 
        {
            JOptionPane.showMessageDialog(null,"[FROM] Station and [TO] Station can't be Same!1"
                    + "   Please Try Again!!",
                    "Invalid Selection",JOptionPane.ERROR_MESSAGE);
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==7) 
        {
            JOptionPane.showMessageDialog(null,"[FROM] Station and [TO] Station can't be Same!"
                    + "   Please Try Again!!",
                    "Invalid Selection",JOptionPane.ERROR_MESSAGE);
        }
        else if (FROM_STN.getSelectedIndex()==8 && TO_STN.getSelectedIndex()==8) 
        {
            JOptionPane.showMessageDialog(null,"[FROM] Station and [TO] Station can't be Same!"
                    + "   Please Try Again!!",
                    "Invalid Selection",JOptionPane.ERROR_MESSAGE);
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==0) 
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==6) 
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==1) 
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==2) 
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==0 && TO_STN.getSelectedIndex()==6) 
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==0 && TO_STN.getSelectedIndex()==1) 
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==0 && TO_STN.getSelectedIndex()==2) 
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==6 && TO_STN.getSelectedIndex()==1) 
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==6 && TO_STN.getSelectedIndex()==2) 
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==1 && TO_STN.getSelectedIndex()==2) 
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==4) 
        {
            TRAIN_NO.setText("IRBT002");
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==8) 
        {
            TRAIN_NO.setText("IRBT002");
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==5) 
        {
            TRAIN_NO.setText("IRBT002");
        }
        else if (FROM_STN.getSelectedIndex()==4 && TO_STN.getSelectedIndex()==8) 
        {
            TRAIN_NO.setText("IRBT002");
        }
        else if (FROM_STN.getSelectedIndex()==4 && TO_STN.getSelectedIndex()==5) 
        {
            TRAIN_NO.setText("IRBT002");
        }
        else if (FROM_STN.getSelectedIndex()==8 && TO_STN.getSelectedIndex()==5) 
        {
            TRAIN_NO.setText("IRBT002");
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==3) 
        {
            TRAIN_NO.setText("IRBT003");
        }
        else if (FROM_STN.getSelectedIndex()==2 && TO_STN.getSelectedIndex()==1) 
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==2 && TO_STN.getSelectedIndex()==6) 
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==2 && TO_STN.getSelectedIndex()==0) 
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==2 && TO_STN.getSelectedIndex()==7) 
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==1 && TO_STN.getSelectedIndex()==6) 
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==1 && TO_STN.getSelectedIndex()==0) 
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==1 && TO_STN.getSelectedIndex()==7) 
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==6 && TO_STN.getSelectedIndex()==0) 
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==6 && TO_STN.getSelectedIndex()==7) 
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==0 && TO_STN.getSelectedIndex()==7) 
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==5 && TO_STN.getSelectedIndex()==8) 
        {
            TRAIN_NO.setText("IRBT005");
        }
        else if (FROM_STN.getSelectedIndex()==5 && TO_STN.getSelectedIndex()==4) 
        {
            TRAIN_NO.setText("IRBT005");
        }
        else if (FROM_STN.getSelectedIndex()==5 && TO_STN.getSelectedIndex()==7) 
        {
            TRAIN_NO.setText("IRBT005");
        }
        else if (FROM_STN.getSelectedIndex()==8 && TO_STN.getSelectedIndex()==4) 
        {
            TRAIN_NO.setText("IRBT005");
        }
        else if (FROM_STN.getSelectedIndex()==8 && TO_STN.getSelectedIndex()==7) 
        {
            TRAIN_NO.setText("IRBT005");
        }
        else if (FROM_STN.getSelectedIndex()==4 && TO_STN.getSelectedIndex()==7) 
        {
            TRAIN_NO.setText("IRBT005");
        }
        else if (FROM_STN.getSelectedIndex()==3 && TO_STN.getSelectedIndex()==7) 
        {
            TRAIN_NO.setText("IRBT006");
        }
        else
        {JOptionPane.showMessageDialog(null," NO DIRECT TRAINS AVAILABLE"
                    + "  !! Please Try Again !!",
                    "Invalid Selection",JOptionPane.ERROR_MESSAGE);}
        SEARCH_TRAIN_BTN.setEnabled(false);
        CLASS_1.setEnabled(true);
        CLASS_2.setEnabled(true);
        CLASS_3.setEnabled(true);
        ENTER_PAXDETAILS_BTN.setEnabled(true);
    }//GEN-LAST:event_SEARCH_TRAIN_BTNActionPerformed

    private void FROM_STNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FROM_STNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FROM_STNActionPerformed

    private void BOOK_TICKET_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOOK_TICKET_BTNActionPerformed
           // TODO add your handling code here:
           String TICKET_NO,S1 = null,S2 = null,DOJ,TNo,Class1 = null,P1Name,P1Age,P1Gender = null,P1UID,
                  P2Name,P2Age,P2Gender = null,P2UID,P3Name,P3Age,P3Gender = null,P3UID,
                  P4Name,P4Age,P4Gender = null,P4UID,TotalFare = null;
           TICKET_NO=Ticket_No.getText();
        if (FROM_STN.getSelectedIndex()==0)
            S1="AHMEDABAD - (ADI)";
        else if (FROM_STN.getSelectedIndex()==1)
            S1="BANGLORE CITY - (SBC)";
        else if (FROM_STN.getSelectedIndex()==2)
            S1="CHENNAI CENTRAL - (MAS)";
        else if (FROM_STN.getSelectedIndex()==3)
            S1="JAIPUR - (JP)";
        else if (FROM_STN.getSelectedIndex()==4)
            S1="KANPUR CENTRAL - (CNB)";
        else if (FROM_STN.getSelectedIndex()==5)
            S1="KOLKATA - (KOAA)";
        else if (FROM_STN.getSelectedIndex()==6)
            S1="MUMBAI CENTRAL - (BCT)";
        else if (FROM_STN.getSelectedIndex()==7)
            S1="NEW DELHI JN - (NDLS)";
        else if (FROM_STN.getSelectedIndex()==8)
            S1="PATNA - (PNBE)";
        if (TO_STN.getSelectedIndex()==0)
            S2="AHMEDABAD - (ADI)";
        else if (TO_STN.getSelectedIndex()==1)
            S2="BANGLORE CITY - (SBC)";
        else if (TO_STN.getSelectedIndex()==2)
            S2="CHENNAI CENTRAL - (MAS)";
        else if (TO_STN.getSelectedIndex()==3)
            S2="JAIPUR - (JP)";
        else if (TO_STN.getSelectedIndex()==4)
            S2="KANPUR CENTRAL - (CNB)";
        else if (TO_STN.getSelectedIndex()==5)
            S2="KOLKATA - (KOAA)";
        else if (TO_STN.getSelectedIndex()==6)
            S2="MUMBAI CENTRAL - (BCT)";
        else if (TO_STN.getSelectedIndex()==7)
            S2="NEW DELHI JN - (NDLS)";
        else if (TO_STN.getSelectedIndex()==8)
            S2="PATNA - (PNBE)";
        DOJ=DOJ_TextField.getText();
        TNo=TRAIN_NO.getText();
        if (CLASS_1.isSelected())
            Class1="FIRST CLASS";
        if (CLASS_2.isSelected())
            Class1="EXECUTIVE CLASS";
        if (CLASS_3.isSelected())
            Class1="ECONOMY";
        P1Name=PAX_1_NAME.getText();
        P1Age=PAX_1_AGE.getText();
        if (PAX_1_GENDER.getSelectedIndex()==0)
            P1Gender="MALE";
        else if (PAX_1_GENDER.getSelectedIndex()==1)
            P1Gender="FEMALE";
        else if (PAX_1_GENDER.getSelectedIndex()==1)
            P1Gender="OTHERS";
        P1UID=PAX_1_UID.getText();
        P2Name=PAX_2_NAME.getText();
        P2Age=PAX_2_AGE.getText();
        if (PAX_2_GENDER.getSelectedIndex()==0)
            P2Gender="MALE";
        else if (PAX_2_GENDER.getSelectedIndex()==1)
            P2Gender="FEMALE";
        else if (PAX_2_GENDER.getSelectedIndex()==1)
            P2Gender="OTHERS";
        P2UID=PAX_2_UID.getText();
        P3Name=PAX_3_NAME.getText();
        P3Age=PAX_3_AGE.getText();
        if (PAX_3_GENDER.getSelectedIndex()==0)
            P3Gender="MALE";
        else if (PAX_3_GENDER.getSelectedIndex()==1)
            P3Gender="FEMALE";
        else if (PAX_3_GENDER.getSelectedIndex()==1)
            P3Gender="OTHERS";
        P3UID=PAX_3_UID.getText();
        P4Name=PAX_4_NAME.getText();
        P4Age=PAX_4_AGE.getText();
        if (PAX_4_GENDER.getSelectedIndex()==0)
            P4Gender="MALE";
        else if (PAX_4_GENDER.getSelectedIndex()==1)
            P4Gender="FEMALE";
        else if (PAX_4_GENDER.getSelectedIndex()==1)
            P4Gender="OTHERS";
        P4UID=PAX_4_UID.getText();
        TotalFare=TOTAL_FARE.getText();
        int p= JOptionPane.showConfirmDialog(null,"Continue to BOOK TICKET",
                "BOOK TICKET - INDIAN RAILWAYS",JOptionPane.YES_NO_OPTION);
        if (p==0){
        try {
            Class.forName("java.sql.DriverManager");
            con=DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/aman","root","tiger");
            stmt=con.createStatement();
            query= "insert into bullettrain_ticket values"
                    + "('"+TICKET_NO+"','"+S1+"','"+S2+"','"+DOJ+"',"
                    + "'"+TNo+"','"+Class1+"','"+P1Name+"','"+P1Age+"',"
                    + "'"+P1Gender+"','"+P1UID+"','"+P2Name+"',"
                    + "'"+P2Age+"','"+P2Gender+"','"+P2UID+"',"
                    + "'"+P3Name+"','"+P3Age+"','"+P3Gender+"',"
                    + "'"+P3UID+"','"+P4Name+"','"+P4Age+"',"
                    + "'"+P4Gender+"','"+P4UID+"','"+TotalFare+"')";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(this,"Booking Processed Successfully");
            PRINT_TICKET_BTN.setEnabled(true);
        }
            catch(Exception e)
        {JOptionPane.showMessageDialog(this,e.getMessage());}
        }
    }//GEN-LAST:event_BOOK_TICKET_BTNActionPerformed

    private void FARE_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FARE_BTNActionPerformed
        // TODO add your handling code here:
        String F = null;
        double PAXFARE;
        String AF = null;
        String CHF = null;
        double GST;
        double TotalFare;
        String CF = null;
        double BaseFare;
        double TBaseFare;
        if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==0) 
        {
            F="4627";
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==6) 
        {
            F="6937";
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==1) 
        {
            F="6307";
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==2) 
        {
            F="6623";
        }
        else if (FROM_STN.getSelectedIndex()==0 && TO_STN.getSelectedIndex()==6) 
        {
            F="3875";
        }
        else if (FROM_STN.getSelectedIndex()==0 && TO_STN.getSelectedIndex()==1) 
        {
            F="6375";
        }
        else if (FROM_STN.getSelectedIndex()==0 && TO_STN.getSelectedIndex()==2) 
        {
            F="6185";
        }
        else if (FROM_STN.getSelectedIndex()==6 && TO_STN.getSelectedIndex()==1) 
        {
            F="5493";
        }
        else if (FROM_STN.getSelectedIndex()==6 && TO_STN.getSelectedIndex()==2) 
        {
            F="6843";
        }
        else if (FROM_STN.getSelectedIndex()==1 && TO_STN.getSelectedIndex()==2) 
        {
            F="1336";
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==4) 
        {
            F="3787";
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==8) 
        {
            F="5363";
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==5) 
        {
            F="7863";
        }
        else if (FROM_STN.getSelectedIndex()==4 && TO_STN.getSelectedIndex()==8) 
        {
            F="3698";
        }
        else if (FROM_STN.getSelectedIndex()==4 && TO_STN.getSelectedIndex()==5) 
        {
            F="6469";
        }
        else if (FROM_STN.getSelectedIndex()==8 && TO_STN.getSelectedIndex()==5) 
        {
            F="3652";
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==3) 
        {
            F="3787";
        }
        else if (FROM_STN.getSelectedIndex()==2 && TO_STN.getSelectedIndex()==1) 
        {
            F="1336";
        }
        else if (FROM_STN.getSelectedIndex()==2 && TO_STN.getSelectedIndex()==6) 
        {
            F="6483";
        }
        else if (FROM_STN.getSelectedIndex()==2 && TO_STN.getSelectedIndex()==0) 
        {
            F="6185";
        }
        else if (FROM_STN.getSelectedIndex()==2 && TO_STN.getSelectedIndex()==7) 
        {
            F="6623";
        }
        else if (FROM_STN.getSelectedIndex()==1 && TO_STN.getSelectedIndex()==6) 
        {
            F="5493";
        }
        else if (FROM_STN.getSelectedIndex()==1 && TO_STN.getSelectedIndex()==0) 
        {
            F="6375";
        }
        else if (FROM_STN.getSelectedIndex()==1 && TO_STN.getSelectedIndex()==7) 
        {
            F="6307";
        }
        else if (FROM_STN.getSelectedIndex()==6 && TO_STN.getSelectedIndex()==0) 
        {
            F="3865";
        }
        else if (FROM_STN.getSelectedIndex()==6 && TO_STN.getSelectedIndex()==7) 
        {
            F="6937";
        }
        else if (FROM_STN.getSelectedIndex()==0 && TO_STN.getSelectedIndex()==7) 
        {
            F="4627";
        }
        else if (FROM_STN.getSelectedIndex()==5 && TO_STN.getSelectedIndex()==8) 
        {
            F="3652";
        }
        else if (FROM_STN.getSelectedIndex()==5 && TO_STN.getSelectedIndex()==4) 
        {
            F="6469";
        }
        else if (FROM_STN.getSelectedIndex()==5 && TO_STN.getSelectedIndex()==7) 
        {
            F="7863";
        }
        else if (FROM_STN.getSelectedIndex()==8 && TO_STN.getSelectedIndex()==4) 
        {
            F="3698";
        }
        else if (FROM_STN.getSelectedIndex()==8 && TO_STN.getSelectedIndex()==7) 
        {
            F="5363";
        }
        else if (FROM_STN.getSelectedIndex()==4 && TO_STN.getSelectedIndex()==7) 
        {
            F="3787";
        }
        else if (FROM_STN.getSelectedIndex()==3 && TO_STN.getSelectedIndex()==7) 
        {
            F="3787";
        }
        double FA=Double.parseDouble(F);
        if (CLASS_1.isSelected())
            CF="0.7";
        else if (CLASS_2.isSelected())
            CF="0.5";
        else if (CLASS_3.isSelected())
            CF="0.2";
        double CFF=Double.parseDouble(CF);
        double CLASSF=(CFF*FA);
        if (NO_OF_ADULTS.getSelectedIndex()==0)
            AF="1";
        else if (NO_OF_ADULTS.getSelectedIndex()==1)
            AF="2";
        else if (NO_OF_ADULTS.getSelectedIndex()==2)
            AF="3";
        else if (NO_OF_ADULTS.getSelectedIndex()==3)
            AF="4";
        double AFF=Double.parseDouble(AF);
        if (NO_OF_CHILD.getSelectedIndex()==0)
            CHF="0";
        else if (NO_OF_CHILD.getSelectedIndex()==1)
            CHF="0.5";
        else if (NO_OF_CHILD.getSelectedIndex()==2)
            CHF="1";
        else if (NO_OF_CHILD.getSelectedIndex()==3)
            CHF="1.5";
        else if (NO_OF_CHILD.getSelectedIndex()==4)
            CHF="2";
        double CHFF=Double.parseDouble(CHF);
        PAXFARE=(AFF+CHFF);
        BaseFare=(CLASSF+FA);
        TBaseFare=(PAXFARE*BaseFare);
        GST=(TBaseFare*0.5);
        TotalFare=TBaseFare+GST;
        int TFFF=(int) Math.round(TotalFare);
        TOTAL_FARE.setText(""+TFFF);
        BOOK_TICKET_BTN.setEnabled(true);
        RESET_BTN_2.setEnabled(true);
        
    }//GEN-LAST:event_FARE_BTNActionPerformed

    private void MAIN_PAGE_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAIN_PAGE_BTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
            Main_Form Info= new Main_Form();
            Info.setVisible(true);
    }//GEN-LAST:event_MAIN_PAGE_BTNActionPerformed

    private void RESET_BTN_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESET_BTN_1ActionPerformed
        // TODO add your handling code here:
        FROM_STN.setSelectedIndex(0);
        TO_STN.setSelectedIndex(0);
        DOJ_TextField.setText("");
        SEARCH_TRAIN_BTN.setEnabled(true);
        CLASS_1.setEnabled(false);
        CLASS_2.setEnabled(false);
        CLASS_3.setEnabled(false);
        ENTER_PAXDETAILS_BTN.setEnabled(false);
    }//GEN-LAST:event_RESET_BTN_1ActionPerformed

    private void ENTER_PAXDETAILS_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENTER_PAXDETAILS_BTNActionPerformed
        // TODO add your handling code here:
        NO_OF_ADULTS.setEnabled(true);
        NO_OF_CHILD.setEnabled(true);
        PAX_1_NAME.setEditable(true);
        PAX_2_NAME.setEditable(true);
        PAX_3_NAME.setEditable(true);
        PAX_4_NAME.setEditable(true);
        PAX_1_AGE.setEditable(true);
        PAX_2_AGE.setEditable(true);
        PAX_3_AGE.setEditable(true);
        PAX_4_AGE.setEditable(true);
        PAX_1_GENDER.setEnabled(true);
        PAX_2_GENDER.setEnabled(true);
        PAX_3_GENDER.setEnabled(true);
        PAX_4_GENDER.setEnabled(true);
        PAX_1_UID.setEditable(true);
        PAX_2_UID.setEditable(true);
        PAX_3_UID.setEditable(true);
        PAX_4_UID.setEditable(true);
        FARE_BTN.setEnabled(true);
        
    }//GEN-LAST:event_ENTER_PAXDETAILS_BTNActionPerformed

    private void RESET_BTN_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESET_BTN_2ActionPerformed
        // TODO add your handling code here:
        NO_OF_ADULTS.setEnabled(false);
        NO_OF_CHILD.setEnabled(false);
        PAX_1_NAME.setEditable(false);
        PAX_2_NAME.setEditable(false);
        PAX_3_NAME.setEditable(false);
        PAX_4_NAME.setEditable(false);
        PAX_1_AGE.setEditable(false);
        PAX_2_AGE.setEditable(false);
        PAX_3_AGE.setEditable(false);
        PAX_4_AGE.setEditable(false);
        PAX_1_GENDER.setEnabled(false);
        PAX_2_GENDER.setEnabled(false);
        PAX_3_GENDER.setEnabled(false);
        PAX_4_GENDER.setEnabled(false);
        PAX_1_UID.setEditable(false);
        PAX_2_UID.setEditable(false);
        PAX_3_UID.setEditable(false);
        PAX_4_UID.setEditable(false);
        FARE_BTN.setEnabled(false);
        PAX_1_NAME.setEnabled(false);
        PAX_2_NAME.setEnabled(false);
        PAX_3_NAME.setEnabled(false);
        PAX_4_NAME.setEnabled(false);
        PAX_1_AGE.setEnabled(false);
        PAX_2_AGE.setEnabled(false);
        PAX_3_AGE.setEnabled(false);
        PAX_4_AGE.setEnabled(false);
        PAX_1_UID.setEnabled(false);
        PAX_2_UID.setEnabled(false);
        PAX_3_UID.setEnabled(false);
        PAX_4_UID.setEnabled(false);
    }//GEN-LAST:event_RESET_BTN_2ActionPerformed

    private void PRINT_TICKET_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRINT_TICKET_BTNActionPerformed
        String Class1 = null;
        String S1 = null;
        // TODO add your handling code here:
        if (FROM_STN.getSelectedIndex()==0)
            S1="AHMEDABAD - (ADI)";
        else if (FROM_STN.getSelectedIndex()==1)
            S1="BANGLORE CITY - (SBC)";
        else if (FROM_STN.getSelectedIndex()==2)
            S1="CHENNAI CENTRAL - (MAS)";
        else if (FROM_STN.getSelectedIndex()==3)
            S1="JAIPUR - (JP)";
        else if (FROM_STN.getSelectedIndex()==4)
            S1="KANPUR CENTRAL - (CNB)";
        else if (FROM_STN.getSelectedIndex()==5)
            S1="KOLKATA - (KOAA)";
        else if (FROM_STN.getSelectedIndex()==6)
            S1="MUMBAI CENTRAL - (BCT)";
        else if (FROM_STN.getSelectedIndex()==7)
            S1="NEW DELHI JN - (NDLS)";
        else if (FROM_STN.getSelectedIndex()==8)
            S1="PATNA - (PNBE)";
        String S2 = null;
        if (TO_STN.getSelectedIndex()==0)
            S2="AHMEDABAD - (ADI)";
        else if (TO_STN.getSelectedIndex()==1)
            S2="BANGLORE CITY - (SBC)";
        else if (TO_STN.getSelectedIndex()==2)
            S2="CHENNAI CENTRAL - (MAS)";
        else if (TO_STN.getSelectedIndex()==3)
            S2="JAIPUR - (JP)";
        else if (TO_STN.getSelectedIndex()==4)
            S2="KANPUR CENTRAL - (CNB)";
        else if (TO_STN.getSelectedIndex()==5)
            S2="KOLKATA - (KOAA)";
        else if (TO_STN.getSelectedIndex()==6)
            S2="MUMBAI CENTRAL - (BCT)";
        else if (TO_STN.getSelectedIndex()==7)
            S2="NEW DELHI JN - (NDLS)";
        else if (TO_STN.getSelectedIndex()==8)
            S2="PATNA - (PNBE)";
        if (CLASS_1.isSelected())
            Class1="FIRST CLASS";
        if (CLASS_2.isSelected())
            Class1="EXECUTIVE CLASS";
        if (CLASS_3.isSelected())
            Class1="ECONOMY";
        String AF = null;
        if (NO_OF_ADULTS.getSelectedIndex()==0)
            AF="1";
        else if (NO_OF_ADULTS.getSelectedIndex()==1)
            AF="2";
        else if (NO_OF_ADULTS.getSelectedIndex()==2)
            AF="3";
        else if (NO_OF_ADULTS.getSelectedIndex()==3)
            AF="4";
        String CHF = null;
        if (NO_OF_CHILD.getSelectedIndex()==0)
            CHF="0";
        else if (NO_OF_CHILD.getSelectedIndex()==1)
            CHF="1";
        else if (NO_OF_CHILD.getSelectedIndex()==2)
            CHF="2";
        else if (NO_OF_CHILD.getSelectedIndex()==3)
            CHF="3";
        else if (NO_OF_CHILD.getSelectedIndex()==4)
            CHF="4";
        String P1Gender = null;
        if (PAX_1_GENDER.getSelectedIndex()==0)
            P1Gender="MALE";
        else if (PAX_1_GENDER.getSelectedIndex()==1)
            P1Gender="FEMALE";
        else if (PAX_1_GENDER.getSelectedIndex()==1)
            P1Gender="OTHERS";
        if (PAX_2_GENDER.getSelectedIndex()==0)
            P1Gender="MALE";
        else if (PAX_2_GENDER.getSelectedIndex()==1)
            P1Gender="FEMALE";
        else if (PAX_2_GENDER.getSelectedIndex()==1)
            P1Gender="OTHERS";
        String P2Gender = null;
        if (PAX_2_GENDER.getSelectedIndex()==0)
            P2Gender="MALE";
        else if (PAX_2_GENDER.getSelectedIndex()==1)
            P2Gender="FEMALE";
        else if (PAX_2_GENDER.getSelectedIndex()==1)
            P2Gender="OTHERS";
        String P3Gender = null;
        if (PAX_3_GENDER.getSelectedIndex()==0)
            P3Gender="MALE";
        else if (PAX_3_GENDER.getSelectedIndex()==1)
            P3Gender="FEMALE";
        else if (PAX_3_GENDER.getSelectedIndex()==1)
            P3Gender="OTHERS";
        String P4Gender = null;
        if (PAX_4_GENDER.getSelectedIndex()==0)
            P4Gender="MALE";
        else if (PAX_4_GENDER.getSelectedIndex()==1)
            P4Gender="FEMALE";
        else if (PAX_4_GENDER.getSelectedIndex()==1)
            P4Gender="OTHERS";
        PRINT_TICKET receive = new PRINT_TICKET();
        PRINT_TICKET.TICKET_NO.setText(Ticket_No.getText());
        PRINT_TICKET.TRAIN_NO.setText(TRAIN_NO.getText());
        PRINT_TICKET.CLASS1.setText(Class1);
        PRINT_TICKET.DOJ.setText(DOJ_TextField.getText());
        PRINT_TICKET.FROM_STN.setText(S1);
        PRINT_TICKET.TO_STN.setText(S2);
        PRINT_TICKET.AD.setText(AF);
        PRINT_TICKET.CH.setText(CHF);
        PRINT_TICKET.PAX_1_NAME.setText(PAX_1_NAME.getText());
        PRINT_TICKET.PAX_2_NAME.setText(PAX_2_NAME.getText());
        PRINT_TICKET.PAX_3_NAME.setText(PAX_3_NAME.getText());
        PRINT_TICKET.PAX_4_NAME.setText(PAX_4_NAME.getText());
        PRINT_TICKET.PAX_1_AGE.setText(PAX_1_AGE.getText());
        PRINT_TICKET.PAX_2_AGE.setText(PAX_2_AGE.getText());
        PRINT_TICKET.PAX_3_AGE.setText(PAX_3_AGE.getText());
        PRINT_TICKET.PAX_4_AGE.setText(PAX_4_AGE.getText());
        PRINT_TICKET.PAX_1_UID.setText(PAX_1_UID.getText());
        PRINT_TICKET.PAX_2_UID.setText(PAX_2_UID.getText());
        PRINT_TICKET.PAX_3_UID.setText(PAX_3_UID.getText());
        PRINT_TICKET.PAX_4_UID.setText(PAX_4_UID.getText());
        PRINT_TICKET.PAX_1_GENDER.setText(P1Gender);
        PRINT_TICKET.PAX_2_GENDER.setText(P2Gender);
        PRINT_TICKET.PAX_3_GENDER.setText(P3Gender);
        PRINT_TICKET.PAX_4_GENDER.setText(P4Gender);
        PRINT_TICKET.TOTAL_FARE.setText(TOTAL_FARE.getText());
        receive.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_PRINT_TICKET_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book_a_Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book_a_Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book_a_Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book_a_Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book_a_Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOOK_TICKET_BTN;
    private javax.swing.JRadioButton CLASS_1;
    private javax.swing.JRadioButton CLASS_2;
    private javax.swing.JRadioButton CLASS_3;
    private javax.swing.JTextField DOJ_TextField;
    private javax.swing.JButton ENTER_PAXDETAILS_BTN;
    private javax.swing.JButton FARE_BTN;
    private javax.swing.JComboBox<String> FROM_STN;
    private javax.swing.JButton MAIN_PAGE_BTN;
    private javax.swing.JComboBox<String> NO_OF_ADULTS;
    private javax.swing.JComboBox<String> NO_OF_CHILD;
    private javax.swing.JTextField PAX_1_AGE;
    private javax.swing.JComboBox<String> PAX_1_GENDER;
    private javax.swing.JTextField PAX_1_NAME;
    private javax.swing.JTextField PAX_1_UID;
    private javax.swing.JTextField PAX_2_AGE;
    private javax.swing.JComboBox<String> PAX_2_GENDER;
    private javax.swing.JTextField PAX_2_NAME;
    private javax.swing.JTextField PAX_2_UID;
    private javax.swing.JTextField PAX_3_AGE;
    private javax.swing.JComboBox<String> PAX_3_GENDER;
    private javax.swing.JTextField PAX_3_NAME;
    private javax.swing.JTextField PAX_3_UID;
    private javax.swing.JTextField PAX_4_AGE;
    private javax.swing.JComboBox<String> PAX_4_GENDER;
    private javax.swing.JTextField PAX_4_NAME;
    private javax.swing.JTextField PAX_4_UID;
    private javax.swing.JButton PRINT_TICKET_BTN;
    private javax.swing.JButton RESET_BTN_1;
    private javax.swing.JButton RESET_BTN_2;
    private javax.swing.JButton SEARCH_TRAIN_BTN;
    private javax.swing.JLabel TOTAL_FARE;
    private javax.swing.JComboBox<String> TO_STN;
    private javax.swing.JTextField TRAIN_NO;
    private javax.swing.JTextField Ticket_No;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
