/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RAVISH
 */
public class FARE_ENQUIRY extends javax.swing.JFrame {

    /**
     * Creates new form FARE_ENQUIRY
     */
    public FARE_ENQUIRY() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        MAIN_PAGE_BTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        FROM_STN = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TO_STN = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        CLASS_1 = new javax.swing.JRadioButton();
        CLASS_2 = new javax.swing.JRadioButton();
        CLASS_3 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        NO_OF_ADULTS = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        NO_OF_CHILD = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        FARE_BTN = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TOTAL_FARE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INDIAN RAILWAYS");
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo1.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setText("INDIAN RAILWAYS");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel10.setText("BULLET TRAIN RESERVATION CUM ENQUIRY SYSTEM");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel10))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel9)))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap(732, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("[NDLS] NEW DELHI JN.");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("!! WELCOME TO INDIAN RAILWAYS !!");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("SERVER 1");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(93, 93, 93)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel12)
                .addComponent(jLabel13)
                .addComponent(jLabel14))
        );

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        MAIN_PAGE_BTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MAIN_PAGE_BTN.setText("<< BACK TO MAIN PAGE");
        MAIN_PAGE_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAIN_PAGE_BTNActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("FARE ENQUIRY");

        FROM_STN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FROM_STN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AHMEDABAD - (ADI)", "BANGLORE CITY - (SBC)", "CHENNAI CENTRAL - (MAS)", "JAIPUR - (JP)", "KANPUR CENTRAL - (CNB)", "KOLKATA - (KOAA)", "MUMBAI CENTRAL - (BCT)", "NEW DELHI JN - (NDLS)", "PATNA - (PNBE)" }));
        FROM_STN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FROM_STNActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("FROM:");
        jLabel15.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("TO:");
        jLabel16.setToolTipText("");

        TO_STN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TO_STN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AHMEDABAD - (ADI)", "BANGLORE CITY - (SBC)", "CHENNAI CENTRAL - (MAS)", "JAIPUR - (JP)", "KANPUR CENTRAL - (CNB)", "KOLKATA - (KOAA)", "MUMBAI CENTRAL - (BCT)", "NEW DELHI JN - (NDLS)", "PATNA - (PNBE)" }));
        TO_STN.setToolTipText("");
        TO_STN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TO_STNActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("CLASS:");

        CLASS_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CLASS_1.setText("FIRST CLASS");

        CLASS_2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CLASS_2.setText("EXECUTIVE CLASS");

        CLASS_3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CLASS_3.setText("ECONOMY");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("NO.OF ADULTS");

        NO_OF_ADULTS.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NO_OF_ADULTS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Age>12years");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("NO.OF CHILD");

        NO_OF_CHILD.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NO_OF_CHILD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Age<12years");

        FARE_BTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FARE_BTN.setText("CALCULATE FARE:");
        FARE_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FARE_BTNActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel40.setText("Total Fare:");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TOTAL_FARE.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        TOTAL_FARE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TOTAL_FARE, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TOTAL_FARE, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TO_STN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FROM_STN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CLASS_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CLASS_2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(CLASS_3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NO_OF_ADULTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NO_OF_CHILD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FARE_BTN)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(MAIN_PAGE_BTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(FROM_STN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(TO_STN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(CLASS_1)
                    .addComponent(CLASS_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CLASS_3)
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(NO_OF_ADULTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(NO_OF_CHILD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(28, 28, 28)
                .addComponent(FARE_BTN)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MAIN_PAGE_BTN)
                            .addComponent(jButton4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void MAIN_PAGE_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAIN_PAGE_BTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Main_Form Info= new Main_Form();
        Info.setVisible(true);
    }//GEN-LAST:event_MAIN_PAGE_BTNActionPerformed

    private void FROM_STNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FROM_STNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FROM_STNActionPerformed

    private void TO_STNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TO_STNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TO_STNActionPerformed

    private void FARE_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FARE_BTNActionPerformed
        // TODO add your handling code here:
        String F = null;
        double PAXFARE;
        String AF = null;
        String CHF = null;
        double GST;
        double TotalFare;
        String CF = null;
        double BaseFare;
        double TBaseFare;
        if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==0) 
        {
            F="4627";
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==6) 
        {
            F="6937";
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==1) 
        {
            F="6307";
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==2) 
        {
            F="6623";
        }
        else if (FROM_STN.getSelectedIndex()==0 && TO_STN.getSelectedIndex()==6) 
        {
            F="3875";
        }
        else if (FROM_STN.getSelectedIndex()==0 && TO_STN.getSelectedIndex()==1) 
        {
            F="6375";
        }
        else if (FROM_STN.getSelectedIndex()==0 && TO_STN.getSelectedIndex()==2) 
        {
            F="6185";
        }
        else if (FROM_STN.getSelectedIndex()==6 && TO_STN.getSelectedIndex()==1) 
        {
            F="5493";
        }
        else if (FROM_STN.getSelectedIndex()==6 && TO_STN.getSelectedIndex()==2) 
        {
            F="6843";
        }
        else if (FROM_STN.getSelectedIndex()==1 && TO_STN.getSelectedIndex()==2) 
        {
            F="1336";
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==4) 
        {
            F="3787";
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==8) 
        {
            F="5363";
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==5) 
        {
            F="7863";
        }
        else if (FROM_STN.getSelectedIndex()==4 && TO_STN.getSelectedIndex()==8) 
        {
            F="3698";
        }
        else if (FROM_STN.getSelectedIndex()==4 && TO_STN.getSelectedIndex()==5) 
        {
            F="6469";
        }
        else if (FROM_STN.getSelectedIndex()==8 && TO_STN.getSelectedIndex()==5) 
        {
            F="3652";
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==3) 
        {
            F="3787";
        }
        else if (FROM_STN.getSelectedIndex()==2 && TO_STN.getSelectedIndex()==1) 
        {
            F="1336";
        }
        else if (FROM_STN.getSelectedIndex()==2 && TO_STN.getSelectedIndex()==6) 
        {
            F="6483";
        }
        else if (FROM_STN.getSelectedIndex()==2 && TO_STN.getSelectedIndex()==0) 
        {
            F="6185";
        }
        else if (FROM_STN.getSelectedIndex()==2 && TO_STN.getSelectedIndex()==7) 
        {
            F="6623";
        }
        else if (FROM_STN.getSelectedIndex()==1 && TO_STN.getSelectedIndex()==6) 
        {
            F="5493";
        }
        else if (FROM_STN.getSelectedIndex()==1 && TO_STN.getSelectedIndex()==0) 
        {
            F="6375";
        }
        else if (FROM_STN.getSelectedIndex()==1 && TO_STN.getSelectedIndex()==7) 
        {
            F="6307";
        }
        else if (FROM_STN.getSelectedIndex()==6 && TO_STN.getSelectedIndex()==0) 
        {
            F="3865";
        }
        else if (FROM_STN.getSelectedIndex()==6 && TO_STN.getSelectedIndex()==7) 
        {
            F="6937";
        }
        else if (FROM_STN.getSelectedIndex()==0 && TO_STN.getSelectedIndex()==7) 
        {
            F="4627";
        }
        else if (FROM_STN.getSelectedIndex()==5 && TO_STN.getSelectedIndex()==8) 
        {
            F="3652";
        }
        else if (FROM_STN.getSelectedIndex()==5 && TO_STN.getSelectedIndex()==4) 
        {
            F="6469";
        }
        else if (FROM_STN.getSelectedIndex()==5 && TO_STN.getSelectedIndex()==7) 
        {
            F="7863";
        }
        else if (FROM_STN.getSelectedIndex()==8 && TO_STN.getSelectedIndex()==4) 
        {
            F="3698";
        }
        else if (FROM_STN.getSelectedIndex()==8 && TO_STN.getSelectedIndex()==7) 
        {
            F="5363";
        }
        else if (FROM_STN.getSelectedIndex()==4 && TO_STN.getSelectedIndex()==7) 
        {
            F="3787";
        }
        else if (FROM_STN.getSelectedIndex()==3 && TO_STN.getSelectedIndex()==7) 
        {
            F="3787";
        }
        double FA=Double.parseDouble(F);
        if (CLASS_1.isSelected())
            CF="0.7";
        else if (CLASS_2.isSelected())
            CF="0.5";
        else if (CLASS_3.isSelected())
            CF="0.2";
        double CFF=Double.parseDouble(CF);
        double CLASSF=(CFF*FA);
        if (NO_OF_ADULTS.getSelectedIndex()==0)
            AF="1";
        else if (NO_OF_ADULTS.getSelectedIndex()==1)
            AF="2";
        else if (NO_OF_ADULTS.getSelectedIndex()==2)
            AF="3";
        else if (NO_OF_ADULTS.getSelectedIndex()==3)
            AF="4";
        double AFF=Double.parseDouble(AF);
        if (NO_OF_CHILD.getSelectedIndex()==0)
            CHF="0";
        else if (NO_OF_CHILD.getSelectedIndex()==1)
            CHF="0.5";
        else if (NO_OF_CHILD.getSelectedIndex()==2)
            CHF="1";
        else if (NO_OF_CHILD.getSelectedIndex()==3)
            CHF="1.5";
        else if (NO_OF_CHILD.getSelectedIndex()==4)
            CHF="2";
        double CHFF=Double.parseDouble(CHF);
        PAXFARE=(AFF+CHFF);
        BaseFare=(CLASSF+FA);
        TBaseFare=(PAXFARE*BaseFare);
        GST=(TBaseFare*0.5);
        TotalFare=TBaseFare+GST;
        int TFFF=(int) Math.round(TotalFare);
        TOTAL_FARE.setText(""+TFFF);
    }//GEN-LAST:event_FARE_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FARE_ENQUIRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FARE_ENQUIRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FARE_ENQUIRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FARE_ENQUIRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FARE_ENQUIRY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CLASS_1;
    private javax.swing.JRadioButton CLASS_2;
    private javax.swing.JRadioButton CLASS_3;
    private javax.swing.JButton FARE_BTN;
    private javax.swing.JComboBox<String> FROM_STN;
    private javax.swing.JButton MAIN_PAGE_BTN;
    private javax.swing.JComboBox<String> NO_OF_ADULTS;
    private javax.swing.JComboBox<String> NO_OF_CHILD;
    private javax.swing.JLabel TOTAL_FARE;
    private javax.swing.JComboBox<String> TO_STN;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
