
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RAVISH
 */
public class TRAIN_BETWEEN_STN extends javax.swing.JFrame {

    /**
     * Creates new form TRAIN_BETWEEN_STN
     */
    public TRAIN_BETWEEN_STN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        FROM_STN = new javax.swing.JComboBox<>();
        TO_STN = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SEARCH_TRAIN_BTN = new javax.swing.JButton();
        RESET_BTN_1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        TRAIN_NO = new javax.swing.JTextField();
        MAIN_PAGE_BTN = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INDIAN RAILWAYS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("INDIAN RAILWAYS");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setText("BULLET TRAIN RESERVATION CUM ENQUIRY SYSTEM");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel2)))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap(732, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("[NDLS] NEW DELHI JN.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("!! WELCOME TO INDIAN RAILWAYS !!");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("SERVER 1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(93, 93, 93)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(jLabel6)
                .addComponent(jLabel7))
        );

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setText("EXIT");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        FROM_STN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FROM_STN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AHMEDABAD - (ADI)", "BANGLORE CITY - (SBC)", "CHENNAI CENTRAL - (MAS)", "JAIPUR - (JP)", "KANPUR CENTRAL - (CNB)", "KOLKATA - (KOAA)", "MUMBAI CENTRAL - (BCT)", "NEW DELHI JN - (NDLS)", "PATNA - (PNBE)" }));
        FROM_STN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FROM_STNActionPerformed(evt);
            }
        });

        TO_STN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TO_STN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AHMEDABAD - (ADI)", "BANGLORE CITY - (SBC)", "CHENNAI CENTRAL - (MAS)", "JAIPUR - (JP)", "KANPUR CENTRAL - (CNB)", "KOLKATA - (KOAA)", "MUMBAI CENTRAL - (BCT)", "NEW DELHI JN - (NDLS)", "PATNA - (PNBE)" }));
        TO_STN.setToolTipText("");
        TO_STN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TO_STNActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("FROM:");
        jLabel8.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("TO:");
        jLabel9.setToolTipText("");

        SEARCH_TRAIN_BTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SEARCH_TRAIN_BTN.setText("SEARCH TRAINS");
        SEARCH_TRAIN_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_TRAIN_BTNActionPerformed(evt);
            }
        });

        RESET_BTN_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RESET_BTN_1.setText("RESET");
        RESET_BTN_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESET_BTN_1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("TRAIN AVAILABLE:");

        TRAIN_NO.setEditable(false);
        TRAIN_NO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        MAIN_PAGE_BTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MAIN_PAGE_BTN.setText("<< BACK TO MAIN PAGE");
        MAIN_PAGE_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAIN_PAGE_BTNActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("TRAIN BETWEEN STATIONS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TRAIN_NO, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TO_STN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(FROM_STN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(SEARCH_TRAIN_BTN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RESET_BTN_1)))
                                .addGap(118, 118, 118))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(MAIN_PAGE_BTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton12)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(224, 224, 224))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FROM_STN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TO_STN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SEARCH_TRAIN_BTN)
                    .addComponent(RESET_BTN_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TRAIN_NO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(MAIN_PAGE_BTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void FROM_STNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FROM_STNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FROM_STNActionPerformed

    private void TO_STNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TO_STNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TO_STNActionPerformed

    private void SEARCH_TRAIN_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_TRAIN_BTNActionPerformed
        // TODO add your handling code here:
        if (FROM_STN.getSelectedIndex()==0 && TO_STN.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null,"[FROM] Station and [TO] Station can't be Same!"
                + "   Please Try Again!!",
                "Invalid Selection",JOptionPane.ERROR_MESSAGE);
        }
        else if (FROM_STN.getSelectedIndex()==1 && TO_STN.getSelectedIndex()==1)
        {
            JOptionPane.showMessageDialog(null,"[FROM] Station and [TO] Station can't be Same!"
                + "   Please Try Again!!",
                "Invalid Selection",JOptionPane.ERROR_MESSAGE);
        }
        else if (FROM_STN.getSelectedIndex()==2 && TO_STN.getSelectedIndex()==2)
        {
            JOptionPane.showMessageDialog(null,"[FROM] Station and [TO] Station can't be Same!"
                + "   Please Try Again!!",
                "Invalid Selection",JOptionPane.ERROR_MESSAGE);
        }
        else if (FROM_STN.getSelectedIndex()==3 && TO_STN.getSelectedIndex()==3)
        {
            JOptionPane.showMessageDialog(null,"[FROM] Station and [TO] Station can't be Same!"
                + "   Please Try Again!!",
                "Invalid Selection",JOptionPane.ERROR_MESSAGE);
        }
        else if (FROM_STN.getSelectedIndex()==4 && TO_STN.getSelectedIndex()==4)
        {
            JOptionPane.showMessageDialog(null,"[FROM] Station and [TO] Station can't be Same!"
                + "   Please Try Again!!",
                "Invalid Selection",JOptionPane.ERROR_MESSAGE);
        }
        else if (FROM_STN.getSelectedIndex()==5 && TO_STN.getSelectedIndex()==5)
        {
            JOptionPane.showMessageDialog(null,"[FROM] Station and [TO] Station can't be Same!"
                + "   Please Try Again!!",
                "Invalid Selection",JOptionPane.ERROR_MESSAGE);
        }
        else if (FROM_STN.getSelectedIndex()==6 && TO_STN.getSelectedIndex()==6)
        {
            JOptionPane.showMessageDialog(null,"[FROM] Station and [TO] Station can't be Same!1"
                + "   Please Try Again!!",
                "Invalid Selection",JOptionPane.ERROR_MESSAGE);
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==7)
        {
            JOptionPane.showMessageDialog(null,"[FROM] Station and [TO] Station can't be Same!"
                + "   Please Try Again!!",
                "Invalid Selection",JOptionPane.ERROR_MESSAGE);
        }
        else if (FROM_STN.getSelectedIndex()==8 && TO_STN.getSelectedIndex()==8)
        {
            JOptionPane.showMessageDialog(null,"[FROM] Station and [TO] Station can't be Same!"
                + "   Please Try Again!!",
                "Invalid Selection",JOptionPane.ERROR_MESSAGE);
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==0)
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==6)
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==1)
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==2)
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==0 && TO_STN.getSelectedIndex()==6)
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==0 && TO_STN.getSelectedIndex()==1)
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==0 && TO_STN.getSelectedIndex()==2)
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==6 && TO_STN.getSelectedIndex()==1)
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==6 && TO_STN.getSelectedIndex()==2)
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==1 && TO_STN.getSelectedIndex()==2)
        {
            TRAIN_NO.setText("IRBT001");
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==4)
        {
            TRAIN_NO.setText("IRBT002");
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==8)
        {
            TRAIN_NO.setText("IRBT002");
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==5)
        {
            TRAIN_NO.setText("IRBT002");
        }
        else if (FROM_STN.getSelectedIndex()==4 && TO_STN.getSelectedIndex()==8)
        {
            TRAIN_NO.setText("IRBT002");
        }
        else if (FROM_STN.getSelectedIndex()==4 && TO_STN.getSelectedIndex()==5)
        {
            TRAIN_NO.setText("IRBT002");
        }
        else if (FROM_STN.getSelectedIndex()==8 && TO_STN.getSelectedIndex()==5)
        {
            TRAIN_NO.setText("IRBT002");
        }
        else if (FROM_STN.getSelectedIndex()==7 && TO_STN.getSelectedIndex()==3)
        {
            TRAIN_NO.setText("IRBT003");
        }
        else if (FROM_STN.getSelectedIndex()==2 && TO_STN.getSelectedIndex()==1)
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==2 && TO_STN.getSelectedIndex()==6)
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==2 && TO_STN.getSelectedIndex()==0)
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==2 && TO_STN.getSelectedIndex()==7)
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==1 && TO_STN.getSelectedIndex()==6)
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==1 && TO_STN.getSelectedIndex()==0)
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==1 && TO_STN.getSelectedIndex()==7)
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==6 && TO_STN.getSelectedIndex()==0)
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==6 && TO_STN.getSelectedIndex()==7)
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==0 && TO_STN.getSelectedIndex()==7)
        {
            TRAIN_NO.setText("IRBT004");
        }
        else if (FROM_STN.getSelectedIndex()==5 && TO_STN.getSelectedIndex()==8)
        {
            TRAIN_NO.setText("IRBT005");
        }
        else if (FROM_STN.getSelectedIndex()==5 && TO_STN.getSelectedIndex()==4)
        {
            TRAIN_NO.setText("IRBT005");
        }
        else if (FROM_STN.getSelectedIndex()==5 && TO_STN.getSelectedIndex()==7)
        {
            TRAIN_NO.setText("IRBT005");
        }
        else if (FROM_STN.getSelectedIndex()==8 && TO_STN.getSelectedIndex()==4)
        {
            TRAIN_NO.setText("IRBT005");
        }
        else if (FROM_STN.getSelectedIndex()==8 && TO_STN.getSelectedIndex()==7)
        {
            TRAIN_NO.setText("IRBT005");
        }
        else if (FROM_STN.getSelectedIndex()==4 && TO_STN.getSelectedIndex()==7)
        {
            TRAIN_NO.setText("IRBT005");
        }
        else if (FROM_STN.getSelectedIndex()==3 && TO_STN.getSelectedIndex()==7)
        {
            TRAIN_NO.setText("IRBT006");
        }
        else
        {JOptionPane.showMessageDialog(null," NO DIRECT TRAINS AVAILABLE"
            + "  !! Please Try Again !!",
            "Invalid Selection",JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_SEARCH_TRAIN_BTNActionPerformed

    private void RESET_BTN_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESET_BTN_1ActionPerformed
        // TODO add your handling code here:
        FROM_STN.setSelectedIndex(0);
        TO_STN.setSelectedIndex(0);
        TRAIN_NO.setText("");
        SEARCH_TRAIN_BTN.setEnabled(true);
    }//GEN-LAST:event_RESET_BTN_1ActionPerformed

    private void MAIN_PAGE_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAIN_PAGE_BTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Main_Form Info= new Main_Form();
        Info.setVisible(true);
    }//GEN-LAST:event_MAIN_PAGE_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TRAIN_BETWEEN_STN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TRAIN_BETWEEN_STN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TRAIN_BETWEEN_STN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TRAIN_BETWEEN_STN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TRAIN_BETWEEN_STN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FROM_STN;
    private javax.swing.JButton MAIN_PAGE_BTN;
    private javax.swing.JButton RESET_BTN_1;
    private javax.swing.JButton SEARCH_TRAIN_BTN;
    private javax.swing.JComboBox<String> TO_STN;
    private javax.swing.JTextField TRAIN_NO;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
